"""Added photo column to bonus_tasks

Revision ID: 21523b62e24e
Revises: d520163d0219
Create Date: 2024-06-18 13:40:02.614886

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '21523b62e24e'
down_revision: Union[str, None] = 'd520163d0219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_tasks', sa.Column('photo', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonus_tasks', 'photo')
    # ### end Alembic commands ###
