"""Removed nullability from bonus_task_id column and added completed_at column at bonus_tasks_completition

Revision ID: c8857b073c48
Revises: 39c33c143630
Create Date: 2024-06-19 18:57:13.132616

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8857b073c48'
down_revision: Union[str, None] = '39c33c143630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_tasks_completition', sa.Column('completed_at', sa.DateTime(), nullable=False))
    op.alter_column('bonus_tasks_completition', 'bonus_task_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonus_tasks_completition', 'bonus_task_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('bonus_tasks_completition', 'completed_at')
    # ### end Alembic commands ###
