"""Changed fields at referral_links

Revision ID: 4d6c97e80aa6
Revises: efd2604d3c8f
Create Date: 2024-06-29 13:30:41.977790

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d6c97e80aa6'
down_revision: Union[str, None] = 'efd2604d3c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_links', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_links', 'is_active')
    # ### end Alembic commands ###
