"""Created games table

Revision ID: 264b00a59be5
Revises: 6f03fa78e57d
Create Date: 2024-06-26 20:21:54.108511

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '264b00a59be5'
down_revision: Union[str, None] = '6f03fa78e57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('marked_as_suspicious', sa.Boolean(), nullable=False),
    sa.Column('on_fraud_check', sa.Boolean(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_games_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_marked_as_suspicious'), 'games', ['marked_as_suspicious'], unique=False)
    op.create_index(op.f('ix_games_on_fraud_check'), 'games', ['on_fraud_check'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_on_fraud_check'), table_name='games')
    op.drop_index(op.f('ix_games_marked_as_suspicious'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
