"""Added description field to bonus_tasks

Revision ID: 6cbb921b792a
Revises: 21523b62e24e
Create Date: 2024-06-19 17:23:22.972858

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6cbb921b792a'
down_revision: Union[str, None] = '21523b62e24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_tasks', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonus_tasks', 'description')
    # ### end Alembic commands ###
