"""Added indexes

Revision ID: 127a6667e9e2
Revises: 96dec446ddc0
Create Date: 2024-06-25 11:22:52.892620

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '127a6667e9e2'
down_revision: Union[str, None] = '96dec446ddc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_balance'), 'users', ['balance'], unique=False)
    op.create_index(op.f('ix_users_daily_overall_profit'), 'users', ['daily_overall_profit'], unique=False)
    op.create_index(op.f('ix_users_game_alltime_highscore'), 'users', ['game_alltime_highscore'], unique=False)
    op.create_index(op.f('ix_users_game_daily_highscore'), 'users', ['game_daily_highscore'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_game_daily_highscore'), table_name='users')
    op.drop_index(op.f('ix_users_game_alltime_highscore'), table_name='users')
    op.drop_index(op.f('ix_users_daily_overall_profit'), table_name='users')
    op.drop_index(op.f('ix_users_balance'), table_name='users')
    # ### end Alembic commands ###
