"""Created m2m tables

Revision ID: 86e1772893bb
Revises: d31db75bfe82
Create Date: 2024-06-12 19:05:51.239214

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '86e1772893bb'
down_revision: Union[str, None] = 'd31db75bfe82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_tasks_completition',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bonus_task_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['bonus_task_id'], ['bonus_tasks.id'], name=op.f('fk_bonus_tasks_completition_bonus_task_id_bonus_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bonus_tasks_completition_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bonus_tasks_completition'))
    )
    op.create_index(op.f('ix_bonus_tasks_completition_bonus_task_id'), 'bonus_tasks_completition', ['bonus_task_id'], unique=False)
    op.create_index(op.f('ix_bonus_tasks_completition_user_id'), 'bonus_tasks_completition', ['user_id'], unique=False)
    op.create_table('daily_rewards_completition',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bonus_task_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['bonus_task_id'], ['bonus_tasks.id'], name=op.f('fk_daily_rewards_completition_bonus_task_id_bonus_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_rewards_completition_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_rewards_completition'))
    )
    op.create_index(op.f('ix_daily_rewards_completition_bonus_task_id'), 'daily_rewards_completition', ['bonus_task_id'], unique=False)
    op.create_index(op.f('ix_daily_rewards_completition_user_id'), 'daily_rewards_completition', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_rewards_completition_user_id'), table_name='daily_rewards_completition')
    op.drop_index(op.f('ix_daily_rewards_completition_bonus_task_id'), table_name='daily_rewards_completition')
    op.drop_table('daily_rewards_completition')
    op.drop_index(op.f('ix_bonus_tasks_completition_user_id'), table_name='bonus_tasks_completition')
    op.drop_index(op.f('ix_bonus_tasks_completition_bonus_task_id'), table_name='bonus_tasks_completition')
    op.drop_table('bonus_tasks_completition')
    # ### end Alembic commands ###
