"""Added used_webapp field at users

Revision ID: efd2604d3c8f
Revises: b769ddc95273
Create Date: 2024-06-28 10:45:23.477044

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'efd2604d3c8f'
down_revision: Union[str, None] = 'b769ddc95273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('used_webapp', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'used_webapp')
    # ### end Alembic commands ###
