"""Changed id column and added access_id column at bonus_tasks

Revision ID: 7fea4b9f214a
Revises: ab469be04ff3
Create Date: 2024-06-30 15:04:36.276835

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7fea4b9f214a'
down_revision: Union[str, None] = 'ab469be04ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_tasks', sa.Column('access_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(op.f('uq_bonus_tasks_access_id'), 'bonus_tasks', ['access_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_bonus_tasks_access_id'), 'bonus_tasks', type_='unique')
    op.drop_column('bonus_tasks', 'access_id')
    # ### end Alembic commands ###
