"""Changed reward field to reward_amount at bonus_tasks

Revision ID: 5e3e8b837dde
Revises: c8857b073c48
Create Date: 2024-06-19 19:22:50.652527

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e3e8b837dde'
down_revision: Union[str, None] = 'c8857b073c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_tasks', sa.Column('reward_amount', sa.Integer(), nullable=False))
    op.drop_column('bonus_tasks', 'reward')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_tasks', sa.Column('reward', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bonus_tasks', 'reward_amount')
    # ### end Alembic commands ###
