"""Added referral_balance field

Revision ID: 6f03fa78e57d
Revises: 127a6667e9e2
Create Date: 2024-06-25 19:22:36.022724

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f03fa78e57d'
down_revision: Union[str, None] = '127a6667e9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_balance', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_balance')
    # ### end Alembic commands ###
