"""Changed fields in users table

Revision ID: 96dec446ddc0
Revises: e11cc1f1bcc4
Create Date: 2024-06-24 18:44:21.735738

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96dec446ddc0'
down_revision: Union[str, None] = 'e11cc1f1bcc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_registration_bonus', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('daily_overall_profit', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('game_daily_highscore', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('game_alltime_highscore', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('users', 'earned_from_referrals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('earned_from_referrals', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False))
    op.drop_column('users', 'game_alltime_highscore')
    op.drop_column('users', 'game_daily_highscore')
    op.drop_column('users', 'daily_overall_profit')
    op.drop_column('users', 'referral_registration_bonus')
    # ### end Alembic commands ###
