"""Changed check_access_data field to access_data

Revision ID: 39c33c143630
Revises: 6cbb921b792a
Create Date: 2024-06-19 17:33:11.687712

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39c33c143630'
down_revision: Union[str, None] = '6cbb921b792a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_tasks', sa.Column('access_data', sa.String(), nullable=True))
    op.drop_column('bonus_tasks', 'check_access_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_tasks', sa.Column('check_access_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bonus_tasks', 'access_data')
    # ### end Alembic commands ###
