"""Added bot_blocked_at field at users

Revision ID: ab469be04ff3
Revises: 5da5e1806310
Create Date: 2024-06-29 14:47:42.920528

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab469be04ff3'
down_revision: Union[str, None] = '5da5e1806310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bot_blocked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bot_blocked_at')
    # ### end Alembic commands ###
