"""Created role field in users

Revision ID: d31db75bfe82
Revises: 8b8964c097d4
Create Date: 2024-06-12 17:25:48.746365

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd31db75bfe82'
down_revision: Union[str, None] = '8b8964c097d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'ADMIN', name='userrole').create(op.get_bind())
    op.add_column('users', sa.Column('role', postgresql.ENUM('USER', 'ADMIN', name='userrole', create_type=False), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum('USER', 'ADMIN', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
