"""Added index on source at users

Revision ID: b769ddc95273
Revises: b7b9d6929102
Create Date: 2024-06-27 18:06:07.322968

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b769ddc95273'
down_revision: Union[str, None] = 'b7b9d6929102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_source'), 'users', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_source'), table_name='users')
    # ### end Alembic commands ###
