"""Made few fields nullable at games

Revision ID: b7b9d6929102
Revises: e3d65684c18a
Create Date: 2024-06-27 12:35:49.091474

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7b9d6929102'
down_revision: Union[str, None] = 'e3d65684c18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'marked_as_suspicious',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('games', 'on_fraud_check',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'on_fraud_check',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('games', 'marked_as_suspicious',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('games', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
